#!/bin/sh

function updatetags()
{
    echo "creating filenametags"
    echo -e "!_TAG_FILE_SORTED\t2\t/2=foldcase/"> filenametags
    find . -not -regex '.*\.\(png\|gif\)'  ! -path "*svn*" -type f -printf "%f\t%p\t1\n" | sort -f>> filenametags
    echo "Done"

    echo "cscope running"
    cscope -Rbq
    echo "cscope done"

    echo "ctags running"
    ctags -R
    echo "cscope done"
}

updatetags
