#!/bin/sh
SERVICE_IP=10.128.178.56
SERVICE_USER=linux3

SERVICE_DIR=/home/linux3/jrd/cyan/M9635AAATWNLZD2033.1
PROJECT_DIR=M9635AAATWNLZD2033.1

function testing()
{
echo "test"
}

function upload_force()
{
if [ -n `echo $SERVICE_DIR | grep $PROJECT_DIR` ]; then
    echo "project name is matched"
else
    echo "project name is not matched"
    exit 0;
fi

if [ -z "$1" ]; then
    exit 0
fi

CURRENT_PATH=`pwd`
filepath=$CURRENT_PATH/$1
DISCREPANCY_PATH=`echo $filepath | sed -n "s/^.*$PROJECT_DIR\(.*\)/\1/p"`

scp -r $filepath $SERVICE_USER@$SERVICE_IP:$SERVICE_DIR/$DISCREPANCY_PATH

echo "Done"
}

function upload_modify()
{
if [ -n `echo $SERVICE_DIR | grep $PROJECT_DIR` ]; then
    echo "project name is matched"
else
    echo "project name is not matched"
    exit 0;
fi

CURRENT_PATH=`pwd`

for filename in `svn st | sed -n 's/^M\s*\(.*\)/\1/p'`;
do
filepath=$CURRENT_PATH/$filename
DISCREPANCY_PATH=`echo $filepath | sed -n "s/^.*$PROJECT_DIR\(.*\)/\1/p"`
scp -r $filepath $SERVICE_USER@$SERVICE_IP:$SERVICE_DIR/$DISCREPANCY_PATH
done
echo "ALL done"
}

function updatetags()
{
echo "creating filenametags"
echo -e "!_TAG_FILE_SORTED\t2\t/2=foldcase/"> filenametags
find . -not -regex '.*\.\(png\|gif\)'  ! -path "*svn*" -type f -printf "%f\t%p\t1\n" | sort -f>> filenametags
echo "Done"

echo "cscope running"
cscope -Rbq
echo "cscope done"

echo "ctags running"
ctags -R
echo "cscope done"
}

if [ "$1" = "-u" ]; then
    upload_modify
elif [ "$1" = "-f" ]; then
    upload_force $2
elif [ "$1" = "-t" ]; then
    updatetags
elif [ "$1" = "-test" ]; then
    testing
else
    echo "Do nothing"
fi
