#! /bin/bash
SERVICE_DIR=/home/linux3/jrd/cyan
SERVICE_IP=10.128.178.56
SERVICE_USER=linux3
SERVICE_PASSWORD=1234567
SVN_PATH=svn://10.128.161.92/datacard/QCT_MDM9x15/branches/M9615ACETWMLZD3033

if [ "$1" == "-u" ]
then
    echo "no1"
elif [ "$1" == "-b" ]
then
    echo "no2"
else
    echo "Do nothing"
fi

function upload_modify()
{
for filename in `svn st | sed -nr 's/^M\s*(.*)/\1/p'`;
do
filepath=`pwd`/$filename
/usr/bin/expect<<-EOF
set time 30
spawn scp -r $filepath $SERVICE_USER@$SERVICE_IP:$SERVICE_DIR/$filename
expect {
"*yes/no" { send "yes\r"; exp_continue }
"*password:" { send "$SERVICE_PASSWORD\r" }
}
interact
expect eof
EOF
done
}

function updatetags()
{
echo "creating filenametags"
echo -e "!_TAG_FILE_SORTED\t2\t/2=foldcase/"> filenametags
find . -not -regex '.*\.\(png\|gif\)'  ! -path "*svn*" -type f -printf "%f\t%p\t1\n" | sort -f>> filenametags
echo "Done"

echo "cscope running"
cscope -Rbq
echo "cscope done"

echo "ctags running"
ctags -R
echo "cscope done"
}


